# Generated by Django 5.1 on 2024-08-28 09:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('redemption_code', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='redemptioncode',
            name='created_by',
        ),
        migrations.AlterField(
            model_name='application',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='redemptioncode',
            name='application',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='redemption_code.application'),
        ),
        migrations.AlterField(
            model_name='redemptioncode',
            name='code',
            field=models.CharField(blank=True, editable=False, max_length=12, unique=True),
        ),
    ]
