services:
  db:
    container_name: mysql-container
    image: mysql:8.0
    restart: always
    volumes:
      - $HOME/mysql:/var/lib/mysql
    env_file:
      - ./.env
    environment:
      - MYSQL_ROOT_PASSWORD=${SQL_ROOT_PASSWORD}
      - MYSQL_USER=${SQL_USER}
      - MYSQL_PASSWORD=${SQL_PASSWORD}
      - MYSQL_DATABASE=${SQL_DATABASE}
    ports:
      - 3306:3306
  django:
    build:
      context: .
      dockerfile: Dockerfile